### ISSUE TITLE
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by stevevaius2015** [mmz-001/knowledge_gpt#13]
After tried to install your app locally I encountered this error on command line `OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions`
How can I fix this issue to run locally? I tried to disable Antivirus as suggested on stackoverflow but no success

**Comment by mmz-001** [comment]
Looks like something is blocking socket access to the default port. Try changing the default port:

```bat
streamlit run main.py --server.port 5998
```
