### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by Jiwanczuk** [mmz-001/knowledge_gpt#14]
Hey! Ive tried cloning this repo, installed all dependencies and then deployed it to streamlit, but I get a "please wait" that never ends and then a connection time-out. Maybe Im missing something?

**Comment by mmz-001** [comment]
This may be a network issue. Try opening it using different connection and let me know if the issue still persists.

**Comment by Jiwanczuk** [comment]
The problem was that I was running streamlit from a "venv" module instead of poetry. I was able to solve it, thank you very much!
