### ISSUE TITLE
This model's maximum context length is 4097 tokens, however you requested 7203 tokens (6947 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

### ISSUE THREAD

**Issue by hujili007** [mmz-001/knowledge_gpt#15]
I uploaded a Chinese txt file(zy.txt).
Input chinese prompt: “什么是精气学说” 
input english prompt："What is the concept of Jingqi theory", 
Whether inputting Chinese or English, the following errors will always occur：
`This model's maximum context length is 4097 tokens, however you requested 7203 tokens (6947 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.`
[zy.txt](https://github.com/mmz-001/knowledge_gpt/files/10738526/zy.txt)

**Comment by ScottishFold007** [comment]
> I uploaded a Chinese txt file(zy.txt). Input chinese prompt: “什么是精气学说” input english prompt："What is the concept of Jingqi theory", Whether inputting Chinese or English, the following errors will always occur： `This model's maximum context length is 4097 tokens, however you requested 7203 tokens (6947 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.` [zy.txt](https://github.com/mmz-001/knowledge_gpt/files/10738526/zy.txt)

就是你的输入长了，考虑检索器那块用本地的吧，答案生成再用线上接口

**Comment by chinesewebman** [comment]
这是通病了。不是输入长，是本地搜到的内容太多，因为这个工具对中文支持差一些。可以试试先用中文分词工具分好了再上传。如果还有问题那就得...换一个应用了。DocsGPT刚修复了这个问题不久。

**Comment by new4u** [comment]
> DocsGPT刚修复了这个问题不久。

现在最新版本修复了吗？需要更新那一块代码？求助
