### ISSUE TITLE
Windows: ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by elisa-chou** [mmz-001/knowledge_gpt#17]
During the "poetry install step", there is an error msg:
"Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it."

Afterwards, when I run "streamlit run main.py", there's error msg:
ModuleNotFoundError: No module named 'openai'

Traceback:
File "C:\Users\souler c\knowledge_gpt\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "C:\Users\souler c\knowledge_gpt\knowledge_gpt\main.py", line 3, in <module>
    from openai.error import OpenAIError

I'll also attach cmd & streamlit detail for you:
![Streamlit _ERROR_MSG](https://user-images.githubusercontent.com/125857551/220054432-c25bb4ff-d867-4882-a933-67251ff853d7.JPG)
[cmd history.txt](https://github.com/mmz-001/knowledge_gpt/files/10782196/cmd.history.txt)

**Comment by mmz-001** [comment]
Looks like somethings wrong with the Python virtual environment. Can you install the `openai` package without using Poetry and see if it works? Other than that you can try creating the virtual environment manually by first deleting the `.venv` folder then creating it with Python:

```shell
python -m venv .venv
```
and try installing the dependencies with Poetry.
