### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by LitPy** [mmz-001/knowledge_gpt#20]
Should I change st.cache and st.experimental_memo? When I try with st.cache_data raises an error for an unexpected argument: "allow_output_mutation=True"

**Comment by mmz-001** [comment]
Yes, we should move to the new `st.cache_data` and `st.cache_resource` caching commands as `st.cache` will be deprecated in the future.

**Comment by openmenta** [comment]
https://www.youtube.com/watch?v=6OozhhI6U4g

Check this out, this guy is working on an open-source alternative to Chat GPT. You could adapt it in some way.

**Comment by David2265** [comment]
hi, is there any solution regards the error above?

**Comment by David2265** [comment]
error solved by changing the st.cache() to st.cache_data() without the parameters

**Comment by swamichandra** [comment]
In utils.py the if I change the decorator right before `def embed_docs(docs: List[Document]) -> VectorStore:` to `st.cache_data()`, I get a 

```
UnhashableParamError: Cannot hash argument 'docs' (of type builtins.list) in 'embed_docs'.

To address this, you can tell Streamlit not to hash this argument by adding a leading underscore to the argument's name in the function signature:

```
How did you fix this?

**Comment by swamichandra** [comment]
> In utils.py if I change the decorator right before `def embed_docs(docs: List[Document]) -> VectorStore:` to `st.cache_data()`, I get a
> 
> ```
> UnhashableParamError: Cannot hash argument 'docs' (of type builtins.list) in 'embed_docs'.
> 
> To address this, you can tell Streamlit not to hash this argument by adding a leading underscore to the argument's name in the function signature:
> ```
> 
> How did you fix this?

Spoke too soon. This is how I fixed it.

```
#@st.cache(allow_output_mutation=True, show_spinner=False)
@st.cache_data()
def embed_docs(_docs: List[Document]) -> VectorStore:
    """Embeds a list of Documents and returns a FAISS index"""
    docsp = _docs

    if not st.session_state.get("OPENAI_API_KEY"):
        raise AuthenticationError(
            "Enter your OpenAI API key in the sidebar. You can get a key at"
            " https://platform.openai.com/account/api-keys."
        )
    else:
        # Embed the chunks
        embeddings = OpenAIEmbeddings(
            openai_api_key=st.session_state.get("OPENAI_API_KEY")
        )  # type: ignore
        index = FAISS.from_documents(docsp, embeddings)

        return index

```
