### ISSUE TITLE
how can I prevent triggle the limit?

### ISSUE THREAD

**Issue by vst212** [mmz-001/knowledge_gpt#3]
Rate limit reached for default-global-with-image-limits in organization org-ks3x7KSLAWTqCJv1Yq9x3FmZ on requests per min. Limit: 60.000000 / min. Current: 80.000000 / min. Contact [support@openai.com](mailto:support@openai.com) if you continue to have issues.

how can I prevent triggle the limit?

Thanks

**Comment by mmz-001** [comment]
Appreciate the heads up. I'll get this fixed ASAP.

**Comment by mmz-001** [comment]
Added a fix. Can you confirm if this is still happening?
