### ISSUE TITLE
Rate limit reached

### ISSUE THREAD

**Issue by bilalnawaz072** [mmz-001/knowledge_gpt#5]
Rate limit reached for default-global-with-image-limits in organization org-Yu8pTMWbwQ0jvtsUA1H1py29 on requests per min. Limit: 60.000000 / min. Current: 70.000000 / min. Contact [support@openai.com](mailto:support@openai.com) if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

**Comment by mmz-001** [comment]
Thanks for flagging this issue. Will fix this soon.

**Comment by mmz-001** [comment]
The issue was patched. Would you mind checking if the problem still exists?

**Comment by SPZel99** [comment]
same for me, it's still there

`error_code=None error_message='Rate limit reached for default-global-with-image-limits in organization xxx on requests per min. Limit: 60.000000 / min. Current: 70.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.' error_param=None error_type=requests message='OpenAI API error received' stream_error=False`
