### ISSUE TITLE
Modifying qa.py to allow for the model kwarg

### ISSUE THREAD

**Issue by kristianjackson** [mmz-001/knowledge_gpt#52]
With the release of gpt-4 via the API there can be a parameter passed for model specifying gpt-3.5-turbo or gpt-4; however the current qa.py expects model to be debug or opanai

**Comment by kristianjackson** [comment]
I already have a code fix that I can apply if you want to create me a new branch

**Comment by mmz-001** [comment]
If you can create a PR for this, that'd be great. Iirc, GPT-4 API access is only available for paid users, so we'll have to check that before adding an option to select the model.

**Comment by mmz-001** [comment]
With the latest release, you can switch between gpt-3.5 and gpt-4.
