### ISSUE TITLE
This model's maximum context length is 4097 tokens, however you requested 5762 tokens (5506 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

### ISSUE THREAD

**Issue by jrt324** [mmz-001/knowledge_gpt#8]
input : Chinese short article(6000 words) 

Ask any question,  follow Error:
This model's maximum context length is 4097 tokens, however you requested 5762 tokens (5506 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

**Comment by mmz-001** [comment]
Glad you pointed this out. Out of curiosity, how big was the input question?

**Comment by jrt324** [comment]
> Glad you pointed this out. Out of curiosity, how big was the input question?

Just 8~20 words. 
eg: Can you tell me about the main characters included in this article

**Comment by mmz-001** [comment]
I'll look into this. It'll be super helpful if you can give me a link to this article so that I repro the error.

**Comment by elisa-chou** [comment]
Having the same problem too.
I'm asking "what is this content mainly about?"

Error msg:
This model's maximum context length is 4097 tokens, however you requested 4812 tokens (4556 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

**Comment by mmz-001** [comment]
@elisa-chou The context length is the prompt size + the requested number of tokens. The issue seems to be that I'm splitting the document according to number of characters, however, it should be split according to the number of tokens. I'll fix this soon.
